### ISSUE TITLE
Release an image for armv7 and armv6

### ISSUE THREAD

**Issue by m040601** [jcorporation/myMPDos#1]
Thanks for your awesome work on myMpd and myMpdos

> myMPDos is a Raspberry Pi image **(aarch64)** 

This means 32bit only Raspberry Pi models prior to the Rpi3 are not supported.
That leaves a lot of Rpi2 and Rpi zeros behind.

I run myMpd on a perfectly capable Rpi2 v1.1 (does not support aarch64).

Since Alpine Linux itself is, https://alpinelinux.org/downloads/ :

>  Designed for RPI 1, 2, 3 and 4. And much more..

Would it possible to release for these archs ?
Automate it through github actions ?

Thanks in advance.

ref: https://en.wikipedia.org/wiki/Raspberry_Pi#Processor

**Comment by jcorporation** [comment]
This should be possible. The build script could be enhanced. But I have no devices for testing.

**Comment by jcorporation** [comment]
I adapted the build script to respect the ARCH environment variable. Creating the build image works, but booting the images for armv7 and armhf does not work. It seems the kernels for armv7 and armhf has no support of the virtual pci devices.

The build image uses the netboot boot files and the virt machine.

**Comment by m040601** [comment]
> booting the images for armv7 and armhf does not work.


>  It seems the kernels for armv7 and armhf has no support of the virtual pci devices.

Could you give an update on the current situation ?

**Comment by jcorporation** [comment]
I use the alpine netboot images to compile the binaries with qemu, but the images for older arm architectures are not booting with qemu. 

Workaround would be to compile with docker buildx. This involves reengineering the compile stage of the build script.

**Comment by m040601** [comment]
Could you provide any updates on this situation ?

I checked and saw that, https://pkgs.alpinelinux.org/packages?name=snapcast&branch=edge&repo=&arch=&maintainer=

 Alpine linux itself provides packages for both armv7h (raspberry 2) and even armhf (raspberry zero)

Is there still any hope to any mympdos releases for these two ?
