### ISSUE TITLE
I am unable to control audio volume

### ISSUE THREAD

**Issue by pirateradiohack** [jcorporation/myMPDos#11]
myMPD shows `Volume: Volumecontrol disabled`.

I have switched the audio hat thanks to `audiohat.sh` to `hifiberry-dac` and the sound works but seems to be turned to maximum volume. 

It seems to be at the OS level since `alsamixer` shows `This sound device does not have any controls.` 
I am pretty sure I can control the sound device under Raspbian. Which makes me think it should work as well with Alpine. 

I am going to investigate but in the meantime if you have any experience or suggestion regarding setting the audio volume I'll gladly take it.

Thanks.

**Comment by jcorporation** [comment]
Eventually Raspian enables the software mixer of mpd by default. myMPDos disables it for sound quality reasons.

**Comment by pirateradiohack** [comment]
Do I understand correctly that it leaves us with only hardware volume controlled DACs for myMPDos?

**Comment by jcorporation** [comment]
You can edit `/etc/mympdos/mympdos.conf` and change the `SOFTWARE_MIXER_FALLBACK` to `true`.

Run `/usr/bin/configmpd.sh`aftwards and restart mpd. This option is also available in the bootstrap file: https://github.com/jcorporation/myMPDos/blob/master/mympdos/bootstrap-advanced.txt

**Comment by pirateradiohack** [comment]
ho great! Thanks for providing a fallback option!

**Comment by pirateradiohack** [comment]
If I remember correctly there is also the possibility to control the DAC with alsa and then tell MPD to use the alsa master as its volume control. Might get better results in terms of sound quality.

**Comment by jcorporation** [comment]
It could be an option for the HifiBerry overlay? The default MPD configuration uses the alsa device directly and does not use the alsa mixer.

**Comment by pirateradiohack** [comment]
> The default MPD configuration uses the alsa device directly

That sounds good to me.

**Comment by jcorporation** [comment]
https://jcorporation.github.io/myMPDos/advanced-topics/customize-mpd
