### ISSUE TITLE
How to add extra software to the image?

### ISSUE THREAD

**Issue by pirateradiohack** [jcorporation/myMPDos#14]
In [another conversation](https://github.com/jcorporation/myMPDos/issues/13) it was mentioned that "extra software" could be installed, by using the `EXTRA_SOFTWARE` config option.

It [looks like](https://github.com/jcorporation/myMPDos/blob/9b2791a6b799e1d93453b66a5b8eb00a54b917d2/mympdos/overlay/etc/local.d/mympdos-bootstrap.start#L361) the list requires valid Alpine packages to be installed with `apk`. 

I need to install a few Python modules. I understand their dependencies can be installed through `apk` if I'm lucky. Some dependencies may require `pip` though, do you have any recommendation in this case?

Regarding the Python modules themselves, I guess the simple way would be to package those to be installable by `apk`, am I correct?
In this case, is there a simple way to provide those packages through a local `apk` repository?

**Comment by jcorporation** [comment]
You can simply add your own scripts and files to the bootstrap overlay: https://github.com/jcorporation/myMPDos/tree/master/mympdos/overlay. Scripts in `etc/local.d` are executed on startup.

Some hints:
- make sure the custom script runs after the standard bootstrap script.
- add `REBOOT=0` to your `bootstrap.txt` file, else the standard bootstrap scripts reboots before your custom script will be executed.
- the custom script should do:
  - remove itself
  - runs `lbu_commit` to save your changes
  - does the final `reboot`

I would prefer to package the missing python modules as apk and add a separate repository. Hosting the repository itself on GitHub works like a charm. Running `pip` should work also, be aware of that `lbu` does not save all changes, only the changes in directories listed by `lbu_include -l` and `/etc` (Reference: https://wiki.alpinelinux.org/wiki/Alpine_local_backup).

**Comment by pirateradiohack** [comment]
Thanks, that's excellent information. Will try that out soon!
