### ISSUE TITLE
The repository may be heavier that it needs to be.

### ISSUE THREAD

**Issue by pirateradiohack** [jcorporation/myMPDos#16]
Not a big deal, but when I cloned this repo, I realized that it's about 700 MB if I recall correctly.  
But nothing inside the repo actually weights this much. The heavy file is in `.git/objects/pack/pack-5708580219d3200d25a4928c77da877ce737e0d0.pack`.  
Which means it's the history of the repo that contains this much.

If it's actually just the overall history then not much can be done. But it could very well be some big file that was committed accidentally and then removed but stayed in the history, like an `.img` for example.  
That can be removed but it requires rewriting history, not sure you want to do that.  
Just my 2 cents, feel free to close if you don't mind about the size. But as I am thinking about cloning the repo each time I need to create a new image I am a bit affected by this.

**Comment by jcorporation** [comment]
You can clone this repo with ` --depth=1`. I think the size comes mainly from the `/repository`  folder that holds the apks.
