### ISSUE TITLE
Self built image cannot use myMPDos repositories

### ISSUE THREAD

**Issue by pirateradiohack** [jcorporation/myMPDos#17]
I have successfully built the image but the first boot fails at:

```
adding repositories and upgrade
...
Adding myMPDos archiv signing public key
...
fetch https://raw.githubusercontent.com/jcorporation/myMPDos/master/repository/aarch64/APKINDEX.tar.gz
ERROR: https://raw.githubusercontent.com/jcorporation/myMPDos/master/repository: UNTRUSTED signature
WARNING: Ignoring https://raw.githubusercontent.com/jcorporation/myMPDos/master/repository: No such file or directory

```

the above error repeats another 2 times. Then the base Alpine linux installs correctly but there is no MPD running nor web server.

I have built the image with `./build.sh build`.

Did I miss something?

**Comment by jcorporation** [comment]
That is a bug. The build script should always include my archive signing key too.

**Comment by pirateradiohack** [comment]
ok and is there anything I can do? Is this something you need to fix on your side?

**Comment by jcorporation** [comment]
I must fix the build / bootstrap fix.

**Comment by jcorporation** [comment]
Should be fixed in current master, please test.

**Comment by pirateradiohack** [comment]
I'm happy to report the error has disappeared, your repository is correctly added and the final result works as expected.

Thank you.
