### ISSUE TITLE
Mympdos alpine repo is unreachable

### ISSUE THREAD

**Issue by koflesinge** [jcorporation/myMPDos#19]
After a few retry, I can't properly install mympdos as the alpine repo seems to be unreachable. A quick visit with a web browser gives me a 404 error.

So on a fresh install, alpine gets installed, the bootstrap file is read and used, but the os can't connect to your server and it doesn't get to install mpd or mympd and so on, ...

Anything you can do ?

**Comment by jcorporation** [comment]
You used the uri `https://raw.githubusercontent.com/jcorporation/myMPDos/master/repository/`? This uri has no directory listing enabled, 404 is the correct behavior.

You should check the reachability with a concrete file, e. g. `https://raw.githubusercontent.com/jcorporation/myMPDos/master/repository/mail@jcgames.de.rsa.pub`.
