### ISSUE TITLE
OS Script failing to execute

### ISSUE THREAD

**Issue by kurtlawrence** [jcorporation/myMPDos#26]
myMPD version: 11.05

**Describe the bug**

I am failing to execute a shell script.

Getting

```
myMPDos authpriv.notice : command not permitted for mympd: /usr/bin/reset-dac-usb-port.sh
```

in the logs.

**Server plattform (please complete the following information):**
 - OS: myMPDos

**Comment by jcorporation** [comment]
This is myMPDos related. You must use doas and configure it to allow the command.

**Comment by kurtlawrence** [comment]
Thanks, @jcorporation.

It took me a little bit to figure out what was going on, so I have opened #27 to help direct others with similar issues.
