### ISSUE TITLE
status.sh fails (location of vcgencmd has moved)

### ISSUE THREAD

**Issue by blackbar-org** [jcorporation/myMPDos#36]
In status.sh vcgencmd is called by absolute path (/opt/vc/bin/vcgencmd) and fails.

find / -name vcgencmd return:
/usr/share/bash-completion/completions/vcgencmd
/usr/bin/vcgencmd

echo $PATH:
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Why calling by absolute path?

**Comment by jcorporation** [comment]
Thanks for reporting this bug. It was called by absolute path because it was previously not in the search path.
