### ISSUE TITLE
How to persist arbitrary files

### ISSUE THREAD

**Issue by stratosgear** [jcorporation/myMPDos#40]
My usecase requires running tailscale for connecting my pi3 to my network (using vpn as keyword here, for anyone having issues with vpn access and similar issues)

Installation, configuration and usage of tailscale works correctly.

But the process of loging in to tailscale does not persist across reboots.  This is because tailscale keeps it's login state in `/var/lib/tailscale/tailscaled.state` (Note: to be verified, as I cannot test this across boots)

How would I be able to persist this file so it is available across reboots? 

Sidenote: I am vaguely familiar with overlays, and I am struggling to understand the exact mechanism that myMPDos is using for the alpine overlays.  Where can I read more about it?

Thanks!

**Comment by jcorporation** [comment]
myMPDos uses the standard lib utility for persistence: https://wiki.alpinelinux.org/wiki/Alpine_local_backup

Simply use `lbu include` to include the desired directories in the lbu backup.

**Comment by stratosgear** [comment]
Confirm this works!  You're the best!
