### ISSUE TITLE
Install failed location in China

### ISSUE THREAD

**Issue by breezecloud** [jcorporation/myMPDos#42]
I am currently installing myMPDos and my location is in China. I have noticed that the internet speed is slow and errors occur frequently when the system is first started to install software. Can I use a Chinese mirror server and how can I set it up?

**Comment by jcorporation** [comment]
Sorry for the late reply. You can simply change the alpine mirror as described in https://wiki.alpinelinux.org/wiki/Repositories if the system is already running.

For the bootstrap process myMPDos uses a random mirror and checks it. This is at the moment not configurable.
