### ISSUE TITLE
No Sound cards are installed

### ISSUE THREAD

**Issue by keithmillar** [jcorporation/myMPDos#45]
The software now appears to be installed, however no sound cards are installed so I can only play back in a browser and not locally on the pi.

**Comment by jcorporation** [comment]
What soundcard is attached to your Pie?

USB soundcards should be detected automatically.
For audio hat’s: https://jcorporation.github.io/myMPDos/References/audio-hats/

The internal soundcard of the Pie is disabled. It Sounds poor.

**Comment by keithmillar** [comment]
I have always used the internal card and it has worked until now.

**Comment by jcorporation** [comment]
It is disabled by the config.txt, you can enable it manually and myMPDos should detect it.

**Comment by keithmillar** [comment]
I have it working with a usb sound card. Thanks very much for your help.

**Comment by pitsi** [comment]
Sorry for resurrecting this, but how do I edit usercfg.txt so as to enable the built-in sound card? I tried opening it with nano, but it says "file '/boot/usercfg.txt' is unwritable".

Fresh installation of 1.6.4, I just changed a few settings (timezone, hostname, motd) and installed nano. I have some experience on alpine, but it is from regular x64 installations.

**Comment by jcorporation** [comment]
You must remount it in rw mode.

`mount -oremount,rw /boot` should do the job.

**Comment by pitsi** [comment]
I think I did something wrong...
```
# mount -oremount,rw /boot
mount: can't find /boot in /proc/mounts
```
and indeed /boot is not in the output of mount!

**Comment by pitsi** [comment]
I did some progress. First and foremost, please ignore the apkovl file part I said above. I will get to that in a future report.

In order to make the card work, I had to load the module and then the system showed it in aplay -l. Do I have to add it to /etc/modules too?
```
# modprobe snd_bcm2835
# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7

```
