### ISSUE TITLE
Support for using the pi and as a Bluetooth speaker

### ISSUE THREAD

**Issue by cristiioan** [jcorporation/myMPDos#6]
Hi,
Is it possible to make this possible to be used and as a Bluetooth speaker. Maybe ruing something similar to [balena-sound](https://github.com/balenalabs/balena-sound)?
It will be quite a nice thing, since right now they interfere one with another and gets annoying.

**Comment by jcorporation** [comment]
myMPDos is designed to act as a MPD server with myMPD as the frontend. Features that are not in this skope are not supported by me.

But you could create a feature request in the balena repository. They could add MPD and myMPD to there solution.
