### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by jerta** [jcorporation/myMPDos#7]
with simple bootstrap file,  install the 0.93 failed.
with ssh, i just this commands to fix
chmod a+w /var/lib/mympd
mympd
(wait for some downloads) and after :
chmod a-w /var/lib/mympd
savereboot.sh
fix
(raspberry 3 v1.2)

**Comment by jcorporation** [comment]
It seems it is the same bug as in https://github.com/jcorporation/myMPD/issues/661. This is fixed in the devel branch already.
